### ISSUE TITLE
RuntimeError: mat1 dim 1 must match mat2 dim 0

### ISSUE THREAD

**Issue by a-ceron** [a-ceron/master-degree#3]
# Descripción
La lógica hasta el entrenamiento se encuentra implementado en el archvio `pyTorch/test-proyects/app/main.py` al pasar por el discriminador los sizes no son los mismosl

# Error observado
```Python
Traceback (most recent call last):
  File "main.py", line 193, in <module>
    main()
  File "main.py", line 191, in main
    test_dataloader, loss_fn, epochs, plot_inter, device, noise_dim)
  File "main.py", line 39, in train
    fake_out = discriminator(gen_img)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ariel/Documents/models-aceron/master-degree/pyTorch/test-proyects/app/models/myFastGAN.py", line 44, in forward
    feat_4 = self.init(z)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 dim 1 must match mat2 dim 0
```

cc: @gibranfp

**Comment by a-ceron** [comment]
Por un momento pensé que se trataba de un problema de dimensiones por lo que modifique las dimensiones de las imagenes usando un transform.Resize en el transformer.

El problema persiste por lo que creo ahora que es un problema en la implementación de los pesos, habrá que ver si se cumplen las dimesiones. Sin embargo las imagenes de entrada comparten el mismo tamaño que las imagenes que se estan usando en el problema original que plantean en el modelo en https://github.com/gibranfp/CursoAprendizajeProfundo/blob/2023-1/notebooks/5e_fastgan.ipynb

**Comment by a-ceron** [comment]
Hardcode la variable `device` a `cpu` el error cambio pero se mantiene igual 

```Python
cpu
Traceback (most recent call last):
  File "main.py", line 193, in <module>
    main()
  File "main.py", line 191, in main
    test_dataloader, loss_fn, epochs, plot_inter, device, noise_dim)
  File "main.py", line 39, in train
    fake_out = discriminator(gen_img)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ariel/Documents/models-aceron/master-degree/pyTorch/test-proyects/app/models/myFastGAN.py", line 44, in forward
    feat_4 = self.init(z)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 93, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/ariel/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py", line 1692, in linear
    output = input.matmul(weight.t())
RuntimeError: mat1 and mat2 shapes cannot be multiplied (12288x32 and 64x2048)
```

**Comment by a-ceron** [comment]
[L190](https://github.com/a-ceron/master-degree/blob/main/pyTorch/test-proyects/app/main.py#L190) Envie dos generadores en el paso de entrenamiento, corrigiendo.
